sudo: false
language: python
cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.cache/shuup/build_resources"
    - "$HOME/.nvm"
env:
  - DEBUG=1
python:
  - "3.6"
install:
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.0/install.sh | bash
  - source ~/.nvm/nvm.sh && nvm install 4
  - pip install -U pip
  - pip install codecov
  - pip install shuup
  - pip install -r test_requirements.txt
script:
  - py.test -ra -vvv --nomigrations --cov
after_success:
  - codecov
